const express = require("express");
const router = express.Router();
const UserRouter = require("./user/router/User.Router");
const GalleryRouter = require("./galleryManagement/gallery/router/GalleryRouter");
const ResponsibilityRouter = require("./reponsibility/router/ResponsibilityRouter");
const MemberRouter = require("./member/router/MemberRouter");
const WardRouter = require("./ward/router/WardRouter");
const WardManagementRouter = require("./wardManagement/router/WardManagementRouter");
const UnitRouter = require("./unit/Router/UnitRouter");
const UnitManagementRouter = require("./unitManagement/router/UnitManagementRouter");
const GalleryCategoryRouter = require("./galleryManagement/galleryCategory/router/GalleryCategoryRouter");
const VideoCategoryRouter = require("./videoManagement/videoCategory/router/VideoCategoryRouter");
const VideoRouter = require("./videoManagement/video/router/VideoRouter");
const BlogCategoryRouter = require("./blogManagement/blogCategory/router/BlogCategoryRouter");
const BlogImageRouter = require("./blogManagement/blog/router/BlogImageRouter");
const BlogRouter = require("./blogManagement/blog/router/BlogRouter");
const HeroBannerRouter = require("./heroBanner/router/HeroBannerRouter");
const FrontViewRouter = require("./website/FrontViewRouter");
const CounterRouter = require("./ManpowerCount/Router/CounterRouter");
const MartyredLeadersRouter = require("./martyredleaders/router/MartyredLeadersRouter");

router.use("/user", UserRouter());
router.use("/gallery", GalleryRouter());
router.use("/responsibility", ResponsibilityRouter());
router.use("/members", MemberRouter());
router.use("/wards", WardRouter());
router.use("/ward-management", WardManagementRouter());
router.use("/units", UnitRouter());
router.use("/unit-management", UnitManagementRouter());
router.use("/gallery-category", GalleryCategoryRouter());
router.use("/video-category", VideoCategoryRouter());
router.use("/video", VideoRouter());
router.use("/blog-category", BlogCategoryRouter());
router.use("/blog/blog-image", BlogImageRouter());
router.use("/blog", BlogRouter());
router.use("/hero-banner", HeroBannerRouter());
router.use("/sbns-counter", CounterRouter());
router.use("/front-view", FrontViewRouter())
router.use("/our-hero",MartyredLeadersRouter());

module.exports = () => router;
